import React, { useState, useMemo, useRef, useEffect } from "react";
import {
  Save,
  ArrowRight,
  Plus,
  Trash2,
  Layers,
  Sparkles,
  Search,
  CheckCircle2,
  Building,
  Lightbulb,
  AlertTriangle,
  ChevronDown,
  ChevronUp,
  X,
  Check,
  CheckSquare,
  Square,
  ListChecks,
} from "lucide-react";
import {
  CenterSettings,
  RoundObservation,
  RoundReport,
  StandardObservationItem,
  STANDARD_ROUND_DEPARTMENTS,
} from "../types";
import { STANDARD_OBSERVATIONS_LIBRARY, OBSERVATION_CATEGORIES } from "../data/standardObservations";
import {
  TODAY_ADDED_OBSERVATION_IDS,
  isTodaySummaryObservation,
  sortWithTodaySummaryFirst,
} from "../data/todayObservationsSummary";
import { findSmartCorrectiveAction, fetchAiCorrectiveAction } from "../utils/correctiveActionEngine";
import {
  getAllCombinedObservations,
  autoPersistObservationsFromRound,
  CUSTOM_OBSERVATIONS_EVENT,
} from "../utils/customObservationsManager";
import {
  DEFAULT_WEEKLY_BALANCED_ROUNDS,
  generateBalancedRoundObservations,
} from "../data/defaultRounds";
import { RoundObservationPickerModal } from "./RoundObservationPickerModal";

interface RoundFormProps {
  initialRound?: RoundReport | null;
  centerSettings: CenterSettings;
  onSave: (round: RoundReport) => void;
  onCancel: () => void;
}

export const RoundForm: React.FC<RoundFormProps> = ({
  initialRound,
  centerSettings,
  onSave,
  onCancel,
}) => {
  const isNewRound = !initialRound;
  const [title, setTitle] = useState<string>(
    initialRound?.title || "تقرير المرور الاسبوعي لمكافحة العدوى"
  );
  const [department, setDepartment] = useState<string>(
    initialRound?.department || ""
  );
  const [day, setDay] = useState<string>(() => {
    if (initialRound?.day) return initialRound.day;
    const dayNames = ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"];
    return dayNames[new Date().getDay()] || "الأحد";
  });
  const [date, setDate] = useState<string>(
    initialRound?.date || new Date().toISOString().split("T")[0].replace(/-/g, "/")
  );
  const [period, setPeriod] = useState<string>(initialRound?.period || "صباحي");
  const [inspector, setInspector] = useState<string>(
    initialRound?.inspector || centerSettings.infectionControlLead || "مشرف مكافحة العدوى"
  );
  const [supervisorRole, setSupervisorRole] = useState<string>(
    initialRound?.supervisorRole || "مشرف مكافحة العدوى"
  );

  const [observations, setObservations] = useState<RoundObservation[]>(() => {
    if (initialRound?.observations && initialRound.observations.length > 0) {
      return initialRound.observations;
    }
    // Default initial row
    return [
      {
        id: `ro-${Date.now()}-1`,
        location: initialRound?.department || "",
        observation: "",
        recommendation: "",
        responsible: "مشرف التمريض / مسؤول مكافحة العدوى",
        status: "in_progress",
      },
    ];
  });

  // Categorized Observations Multi-Select State (default closed to edit report directly)
  const [showObservationBank, setShowObservationBank] = useState<boolean>(false);
  const [isPickerModalOpen, setIsPickerModalOpen] = useState<boolean>(false);
  const [selectedCategory, setSelectedCategory] = useState<string>("الكل");
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [selectedItemIds, setSelectedItemIds] = useState<string[]>([]);
  const [severityFilter, setSeverityFilter] = useState<string>("all");

  // Track which observation row has its autocomplete suggestions dropdown open
  const [activeSuggestionRowId, setActiveSuggestionRowId] = useState<string | null>(null);
  const [dropdownCategoryFilter, setDropdownCategoryFilter] = useState<string>("الكل");

  // AI loading per observation
  const [aiLoadingIdx, setAiLoadingIdx] = useState<number | null>(null);

  // Track auto-generated status for UI badges
  const [autoGeneratedRows, setAutoGeneratedRows] = useState<{ [rowId: string]: boolean }>({});
  const [userEditedRecRows, setUserEditedRecRows] = useState<{ [rowId: string]: boolean }>({});
  const autoGenDebounceTimers = useRef<{ [rowId: string]: any }>({});

  // Success toast for added items
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const tableRef = useRef<HTMLDivElement>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3000);
  };

  // Full standard library items (including custom and reactive updates)
  const [customItems, setCustomItems] = useState<StandardObservationItem[]>(() => getAllCombinedObservations());

  useEffect(() => {
    const handleUpdate = () => {
      setCustomItems(getAllCombinedObservations());
    };
    window.addEventListener(CUSTOM_OBSERVATIONS_EVENT, handleUpdate);
    return () => window.removeEventListener(CUSTOM_OBSERVATIONS_EVENT, handleUpdate);
  }, []);

  const allLibraryItems = customItems;

  const categories = useMemo(() => {
    const cats = new Set<string>();
    cats.add("الكل");
    cats.add("⭐ الملخص (اليوم)");
    // Place standard round departments first
    STANDARD_ROUND_DEPARTMENTS.forEach((d) => cats.add(d));
    allLibraryItems.forEach((i) => cats.add(i.category));
    return Array.from(cats);
  }, [allLibraryItems]);

  const matchItemToDepartment = (item: StandardObservationItem, dept: string) => {
    if (dept === "الكل") return true;
    if (dept === "⭐ الملخص (اليوم)") {
      return TODAY_ADDED_OBSERVATION_IDS.includes(item.id);
    }
    const text = `${item.category} ${item.location} ${item.observation} ${item.recommendation}`.toLowerCase();
    if (dept === "عيادة") {
      return text.includes("عياد") || text.includes("كشف") || text.includes("خارجي");
    }
    if (dept === "فحوصات") {
      return text.includes("فحص") || text.includes("بصر") || text.includes("تشخيص") || text.includes("مختبر") || text.includes("تونوميتر") || text.includes("اشعة") || text.includes("أشعة");
    }
    if (dept === "قسم داخلي") {
      return text.includes("داخلي") || text.includes("تنويم") || text.includes("غرف") || text.includes("نظافة") || text.includes("بيئية") || text.includes("مغسل") || text.includes("نفايات");
    }
    if (dept === "عمليات") {
      return text.includes("عمليات") || text.includes("جراح") || text.includes("فاكو") || text.includes("تعقيم") || text.includes("cssd") || text.includes("تخدير");
    }
    if (dept === "إفاقة" || dept === "افاقة") {
      return text.includes("افاق") || text.includes("إفاق") || text.includes("رعاية") || text.includes("عناية") || text.includes("icu") || text.includes("pacu");
    }
    return item.category === dept || item.location.includes(dept);
  };

  // Filtered observations for the multi-select bank (35 summary items sorted first)
  const filteredBankItems = useMemo(() => {
    const list = allLibraryItems.filter((item) => {
      let matchCat = false;
      if (selectedCategory === "الكل") {
        matchCat = true;
      } else if (selectedCategory === "⭐ الملخص (اليوم)") {
        matchCat = TODAY_ADDED_OBSERVATION_IDS.includes(item.id);
      } else if (STANDARD_ROUND_DEPARTMENTS.includes(selectedCategory as any)) {
        matchCat = matchItemToDepartment(item, selectedCategory);
      } else {
        matchCat = item.category === selectedCategory;
      }

      const matchSev = severityFilter === "all" || item.severity === severityFilter;
      const q = searchQuery.trim().toLowerCase();
      const matchSearch =
        !q ||
        item.observation.toLowerCase().includes(q) ||
        item.recommendation.toLowerCase().includes(q) ||
        item.location.toLowerCase().includes(q) ||
        item.category.toLowerCase().includes(q) ||
        (item.standardRef && item.standardRef.toLowerCase().includes(q));
      return matchCat && matchSev && matchSearch;
    });

    return sortWithTodaySummaryFirst(list);
  }, [allLibraryItems, selectedCategory, severityFilter, searchQuery]);

  // Group items by category for structured layout
  const groupedBankItems = useMemo(() => {
    const groups: { [key: string]: StandardObservationItem[] } = {};
    filteredBankItems.forEach((item) => {
      if (!groups[item.category]) {
        groups[item.category] = [];
      }
      groups[item.category].push(item);
    });
    return groups;
  }, [filteredBankItems]);

  // Toggle single item selection checkbox
  const handleToggleItemSelection = (id: string) => {
    setSelectedItemIds((prev) =>
      prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]
    );
  };

  // Select all currently visible filtered items
  const handleSelectAllVisible = () => {
    const visibleIds = filteredBankItems.map((i) => i.id);
    const allSelected = visibleIds.every((id) => selectedItemIds.includes(id));
    if (allSelected) {
      setSelectedItemIds((prev) => prev.filter((id) => !visibleIds.includes(id)));
    } else {
      setSelectedItemIds((prev) => Array.from(new Set([...prev, ...visibleIds])));
    }
  };

  // Clear all selections
  const handleClearSelections = () => {
    setSelectedItemIds([]);
  };

  // 🌟 Bulk Insert Selected Observations into Round Report 🌟
  const handleAddSelectedToReport = () => {
    if (selectedItemIds.length === 0) {
      alert("يرجى تحديد ملاحظة واحدة على الأقل بالضغط على المربع الصغير لإضافتها.");
      return;
    }

    const selectedItems = allLibraryItems.filter((item) =>
      selectedItemIds.includes(item.id)
    );

    const newRows: RoundObservation[] = selectedItems.map((item, idx) => ({
      id: `ro-bulk-${Date.now()}-${idx}-${Math.random().toString(36).substring(2, 5)}`,
      location: item.location || item.category,
      observation: item.observation,
      recommendation: item.recommendation,
      responsible: item.responsible || "مشرف القسم / مسؤول مكافحة العدوى",
      status: "in_progress",
      dueDate: item.duration || "فوري",
    }));

    setObservations((prev) => {
      // If table only has 1 empty initial row, replace it
      const isSingleEmpty = prev.length === 1 && !prev[0].observation.trim();
      return isSingleEmpty ? newRows : [...prev, ...newRows];
    });

    const count = newRows.length;
    setSelectedItemIds([]);
    showToast(`✅ تمت إضافة (${count}) ملاحظات مختارة بنجاح إلى جدول التقرير`);

    // Smooth scroll down to observations table
    if (tableRef.current) {
      tableRef.current.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  // 🌟 Insert Single Observation from Picker Modal 🌟
  const handleSelectObservationFromPicker = (item: StandardObservationItem) => {
    const newRow: RoundObservation = {
      id: `ro-picker-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      location: item.location || item.category || department || "عام",
      observation: item.observation,
      recommendation: item.recommendation,
      responsible: item.responsible || "مشرف التمريض / مسؤول مكافحة العدوى",
      status: "in_progress",
      dueDate: item.duration || "فوري",
    };

    setObservations((prev) => {
      const isSingleEmpty = prev.length === 1 && !prev[0].observation.trim();
      return isSingleEmpty ? [newRow] : [...prev, newRow];
    });
    showToast(`✅ تمت إضافة ملاحظة (${item.location}) إلى التقرير`);
  };

  // 🌟 Insert Multiple Observations from Picker Modal 🌟
  const handleSelectMultipleObservationsFromPicker = (items: StandardObservationItem[]) => {
    if (items.length === 0) return;

    const newRows: RoundObservation[] = items.map((item, idx) => ({
      id: `ro-picker-bulk-${Date.now()}-${idx}-${Math.random().toString(36).substring(2, 5)}`,
      location: item.location || item.category || department || "عام",
      observation: item.observation,
      recommendation: item.recommendation,
      responsible: item.responsible || "مشرف القسم / مسؤول مكافحة العدوى",
      status: "in_progress",
      dueDate: item.duration || "فوري",
    }));

    setObservations((prev) => {
      const isSingleEmpty = prev.length === 1 && !prev[0].observation.trim();
      return isSingleEmpty ? newRows : [...prev, ...newRows];
    });

    showToast(`✅ تمت إضافة (${items.length}) ملاحظات مختارة بنجاح`);

    if (tableRef.current) {
      tableRef.current.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  // 🌟 State for Balanced Preset dropdown menu 🌟
  const [isBalancedMenuOpen, setIsBalancedMenuOpen] = useState(false);

  // 🌟 Load Balanced Preset (4-5 observations with 1-2 per department) 🌟
  const handleLoadBalancedPreset = (weekNum?: number) => {
    let presetRows: RoundObservation[] = [];
    if (weekNum && weekNum >= 1 && weekNum <= 4) {
      const target = DEFAULT_WEEKLY_BALANCED_ROUNDS[weekNum - 1];
      presetRows = target.observations.map((obs, idx) => ({
        ...obs,
        id: `ro-preset-w${weekNum}-${Date.now()}-${idx}`,
      }));
    } else {
      presetRows = generateBalancedRoundObservations({ count: 5 });
    }

    setObservations(presetRows);
    setIsBalancedMenuOpen(false);
    showToast(`⚡ تم تعبئة التقرير بـ (${presetRows.length}) ملاحظات افتراضية متوازنة عبر كافة الأقسام`);

    if (tableRef.current) {
      tableRef.current.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  // Add empty row manually
  const handleAddObservation = (defaultLocation?: string) => {
    const newId = `ro-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`;
    const newObs: RoundObservation = {
      id: newId,
      location: defaultLocation !== undefined ? defaultLocation : (department || ""),
      observation: "",
      recommendation: "",
      responsible: "مشرف التمريض / مسؤول مكافحة العدوى",
      status: "in_progress",
    };
    setObservations((prev) => [...prev, newObs]);
    setActiveSuggestionRowId(newId);
  };

  const handleUpdateObservation = (
    id: string,
    field: keyof RoundObservation,
    value: any
  ) => {
    if (field === "recommendation") {
      setUserEditedRecRows((prev) => ({ ...prev, [id]: true }));
    }

    setObservations((prev) =>
      prev.map((o) => (o.id === id ? { ...o, [field]: value } : o))
    );

    // 🌟 Automatic Corrective Action Generation upon writing observation 🌟
    if (field === "observation") {
      const text = (value || "").trim();

      // Clear any existing timer for this row
      if (autoGenDebounceTimers.current[id]) {
        clearTimeout(autoGenDebounceTimers.current[id]);
      }

      if (text.length >= 3) {
        const currentObs = observations.find((o) => o.id === id);
        const loc = currentObs?.location || department || "";

        // Immediate smart heuristic matching
        const smartResult = findSmartCorrectiveAction(text, loc);
        if (smartResult) {
          // If recommendation wasn't manually customized by user, auto-populate
          setObservations((prev) =>
            prev.map((o) => {
              if (o.id === id) {
                const shouldUpdateRec = !o.recommendation || !userEditedRecRows[id] || autoGeneratedRows[id];
                const shouldUpdateResp = !o.responsible || o.responsible.includes("مشرف التمريض");
                const shouldUpdateLoc = !o.location && smartResult.suggestedLocation;
                return {
                  ...o,
                  recommendation: shouldUpdateRec ? smartResult.recommendation : o.recommendation,
                  responsible: shouldUpdateResp ? smartResult.responsible : o.responsible,
                  dueDate: smartResult.duration || o.dueDate,
                  location: shouldUpdateLoc ? smartResult.suggestedLocation! : o.location,
                };
              }
              return o;
            })
          );
          setAutoGeneratedRows((prev) => ({ ...prev, [id]: true }));
        }

        // Debounced async AI generation for unique descriptions only if not already resolved by standard library
        if (!smartResult || (smartResult.confidence !== "high" && smartResult.confidence !== "smart_rule")) {
          autoGenDebounceTimers.current[id] = setTimeout(async () => {
            if (text.length >= 6) {
              const aiRes = await fetchAiCorrectiveAction(text, loc);
              if (aiRes && aiRes.recommendation) {
                setObservations((prev) =>
                  prev.map((o) => {
                    if (o.id === id) {
                      const shouldUpdateRec = !o.recommendation || !userEditedRecRows[id] || autoGeneratedRows[id];
                      return {
                        ...o,
                        recommendation: shouldUpdateRec ? aiRes.recommendation : o.recommendation,
                        responsible: aiRes.responsible || o.responsible,
                        dueDate: aiRes.duration || o.dueDate,
                      };
                    }
                    return o;
                  })
                );
                setAutoGeneratedRows((prev) => ({ ...prev, [id]: true }));
              }
            }
          }, 800);
        }
      }
    }
  };

  const handleRemoveObservation = (id: string) => {
    if (autoGenDebounceTimers.current[id]) {
      clearTimeout(autoGenDebounceTimers.current[id]);
    }
    setObservations((prev) => prev.filter((o) => o.id !== id));
    if (activeSuggestionRowId === id) {
      setActiveSuggestionRowId(null);
    }
  };

  // Apply a standard suggestion into a specific row
  const handleSelectSuggestionForRow = (rowId: string, item: StandardObservationItem) => {
    setObservations((prev) =>
      prev.map((o) => {
        if (o.id === rowId) {
          return {
            ...o,
            location: item.location || o.location,
            observation: item.observation,
            recommendation: item.recommendation,
            responsible: item.responsible || o.responsible,
            dueDate: item.duration || o.dueDate,
          };
        }
        return o;
      })
    );
    setAutoGeneratedRows((prev) => ({ ...prev, [rowId]: true }));
    setActiveSuggestionRowId(null);
    showToast(`تم اختيار الملاحظة وتعبئة التوصية والمسؤول تلقائياً`);
  };

  // Trigger manual AI suggest corrective action for a specific observation
  const handleAiSuggestCorrectiveAction = async (idx: number) => {
    const obs = observations[idx];
    if (!obs.observation.trim()) {
      alert("يرجى كتابة الملاحظة أولاً ليقوم الذكاء الاصطناعي باقتراح الإجراء التصحيحي المناسب.");
      return;
    }

    try {
      setAiLoadingIdx(idx);
      const res = await fetchAiCorrectiveAction(obs.observation, obs.location);
      if (res && res.recommendation) {
        handleUpdateObservation(obs.id, "recommendation", res.recommendation);
        if (res.responsible) {
          handleUpdateObservation(obs.id, "responsible", res.responsible);
        }
        if (res.duration) {
          handleUpdateObservation(obs.id, "dueDate", res.duration);
        }
        setAutoGeneratedRows((prev) => ({ ...prev, [obs.id]: true }));
        showToast("✨ تم توليد التوصية والإجراء التصحيحي بنجاح");
      }
    } catch (err) {
      console.error(err);
      alert("تعذر الاتصال بالمساعد الذكي حالياً.");
    } finally {
      setAiLoadingIdx(null);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    const validObs = observations.filter(
      (o) => (o.observation && o.observation.trim().length > 0) || (o.recommendation && o.recommendation.trim().length > 0)
    );

    // 🌟 Auto-persist user observations into custom library bank 🌟
    autoPersistObservationsFromRound(validObs, department);

    const reportToSave: RoundReport = {
      id: initialRound?.id || `round-${Date.now()}`,
      title: title.trim() || "تقرير المرور الاسبوعي لمكافحة العدوى",
      department: department.trim() || undefined,
      day: day.trim() || "الأحد",
      date: date.trim() || new Date().toISOString().split("T")[0],
      period: period.trim() || "صباحي",
      inspector: inspector.trim() || "مشرف مكافحة العدوى",
      supervisorRole: supervisorRole.trim() || "مشرف مكافحة العدوى",
      centerName: centerSettings.centerName,
      observations: validObs,
      createdAt: initialRound?.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    onSave(reportToSave);
  };

  // Helper to filter suggestions for a specific row based on user input text & row location (35 summary items prioritized first)
  const getSuggestionsForRow = (rowObs: RoundObservation) => {
    const query = (rowObs.observation || "").trim().toLowerCase();
    const loc = (rowObs.location || "").trim().toLowerCase();

    const filtered = allLibraryItems.filter((item) => {
      if (dropdownCategoryFilter === "⭐ ملخص اليوم (35)") {
        return TODAY_ADDED_OBSERVATION_IDS.includes(item.id);
      }
      if (dropdownCategoryFilter !== "الكل" && item.category !== dropdownCategoryFilter) {
        return false;
      }

      if (query.length > 0) {
        return (
          item.observation.toLowerCase().includes(query) ||
          item.recommendation.toLowerCase().includes(query) ||
          item.location.toLowerCase().includes(query) ||
          (item.standardRef && item.standardRef.toLowerCase().includes(query))
        );
      }

      if (loc.length > 0) {
        const matchLoc =
          item.location.toLowerCase().includes(loc) ||
          item.category.toLowerCase().includes(loc) ||
          loc.includes(item.location.toLowerCase()) ||
          loc.includes(item.category.toLowerCase());
        return matchLoc;
      }

      return true;
    });

    // 🌟 The 35 summary observations are sorted to the VERY TOP of the suggestions list 🌟
    return sortWithTodaySummaryFirst(filtered, loc);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6 max-w-5xl mx-auto pb-20">
      
      {/* Toast feedback */}
      {toastMessage && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 bg-slate-900 text-white text-xs sm:text-sm px-5 py-3 rounded-2xl shadow-2xl flex items-center gap-2.5 border border-slate-700 animate-in fade-in slide-in-from-bottom-3">
          <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
          <span className="font-bold">{toastMessage}</span>
        </div>
      )}

      {/* Top Action Bar */}
      <div className="bg-white rounded-xl p-4 sm:p-5 border border-slate-200 shadow-xs flex flex-wrap items-center justify-between gap-4 sticky top-16 z-20">
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={onCancel}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 transition-colors cursor-pointer"
          >
            <ArrowRight className="w-4 h-4" />
            <span>إلغاء</span>
          </button>
          <div>
            <h2 className="text-base sm:text-lg font-bold text-slate-900">
              {initialRound ? "تعديل تقرير المرور الميداني" : "تسجيل جولة مرور ميدانية جديدة"}
            </h2>
            <p className="text-xs text-slate-500">
              {initialRound
                ? "تعديل بيانات التقرير وجدول الملاحظات مباشرة"
                : "أدخل بيانات المرور وسجل الملاحظات في الجدول أو اختر من البنك المعتمد"}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          {/* Main Add Observation from Bank & Summary Button */}
          <button
            type="button"
            onClick={() => setIsPickerModalOpen(true)}
            className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-lg text-xs font-bold text-white bg-indigo-600 hover:bg-indigo-700 transition-all shadow-xs cursor-pointer"
          >
            <Sparkles className="w-4 h-4" />
            <span>+ إضافة ملاحظة (من البنك والملخص)</span>
          </button>

          {/* Quick Inline Bank Toggle Button */}
          <button
            type="button"
            onClick={() => setShowObservationBank(!showObservationBank)}
            className={`inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-bold transition-all shadow-2xs cursor-pointer ${
              showObservationBank
                ? "bg-blue-700 text-white shadow-blue-500/20"
                : "text-blue-800 bg-blue-50 hover:bg-blue-100 border border-blue-200"
            }`}
          >
            <ListChecks className="w-4 h-4" />
            <span>{showObservationBank ? "إخفاء بنك الملاحظات" : "تصفح بنك الأقسام بالصفحة"}</span>
            {selectedItemIds.length > 0 && (
              <span className="bg-amber-400 text-slate-900 px-1.5 py-0.2 rounded-full font-black text-[10px]">
                {selectedItemIds.length}
              </span>
            )}
          </button>

          <button
            type="submit"
            className="inline-flex items-center gap-2 px-5 py-2 rounded-lg text-xs sm:text-sm font-bold text-white bg-blue-600 hover:bg-blue-700 transition-colors shadow-xs cursor-pointer"
          >
            <Save className="w-4 h-4" />
            <span>حفظ تقرير المرور ومعاينته</span>
          </button>
        </div>
      </div>

      {/* 1. Basic Metadata (اليوم / التاريخ / الفترة / القائم بالمرور) */}
      <div className="bg-white rounded-xl p-5 sm:p-6 border border-slate-200 shadow-xs space-y-4">
        <h3 className="font-bold text-slate-900 text-sm sm:text-base border-b border-slate-100 pb-3 flex items-center gap-2">
          <Building className="w-4 h-4 text-blue-600" />
          <span>بيانات جولة المرور الميدانية</span>
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div>
            <label className="block text-xs font-bold text-slate-700 mb-1">
              عنوان التقرير
            </label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full text-xs sm:text-sm rounded-lg border border-slate-300 p-2.5 font-bold"
              placeholder="تقرير المرور الاسبوعي لمكافحة العدوى"
              required
            />
          </div>

          <div>
            <label className="block text-xs font-bold text-slate-700 mb-1">اليوم</label>
            <select
              value={day}
              onChange={(e) => setDay(e.target.value)}
              className="w-full text-xs sm:text-sm rounded-lg border border-slate-300 p-2.5"
            >
              <option value="السبت">السبت</option>
              <option value="الأحد">الأحد</option>
              <option value="الاثنين">الاثنين</option>
              <option value="الثلاثاء">الثلاثاء</option>
              <option value="الأربعاء">الأربعاء</option>
              <option value="الخميس">الخميس</option>
              <option value="الجمعة">الجمعة</option>
            </select>
          </div>

          <div>
            <label className="block text-xs font-bold text-slate-700 mb-1">التاريخ</label>
            <input
              type="text"
              value={date}
              onChange={(e) => setDate(e.target.value)}
              className="w-full text-xs sm:text-sm rounded-lg border border-slate-300 p-2.5 font-medium"
              placeholder="2026/06/28"
              required
            />
          </div>

          <div>
            <label className="block text-xs font-bold text-slate-700 mb-1">الفترة</label>
            <select
              value={period}
              onChange={(e) => setPeriod(e.target.value)}
              className="w-full text-xs sm:text-sm rounded-lg border border-slate-300 p-2.5"
            >
              <option value="صباحي">صباحي</option>
              <option value="مسائي">مسائي</option>
              <option value="طوارئ / نوبتجية">طوارئ / نوبتجية</option>
              <option value="مرور مفاجئ">مرور مفاجئ</option>
            </select>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
          <div>
            <label className="block text-xs font-bold text-slate-700 mb-1">
              القائم بالمرور
            </label>
            <input
              type="text"
              value={inspector}
              onChange={(e) => setInspector(e.target.value)}
              className="w-full text-xs sm:text-sm rounded-lg border border-slate-300 p-2.5 font-semibold"
              placeholder="مشرف مكافحة العدوى"
              required
            />
          </div>

          <div>
            <label className="block text-xs font-bold text-slate-700 mb-1">
              المسمى الوظيفي للمشرف
            </label>
            <input
              type="text"
              value={supervisorRole}
              onChange={(e) => setSupervisorRole(e.target.value)}
              className="w-full text-xs sm:text-sm rounded-lg border border-slate-300 p-2.5 font-semibold"
              placeholder="مشرف مكافحة العدوى"
            />
          </div>
        </div>

        {/* اختيار قسم المرور - اختياري مع الاختيارات الخمسة */}
        <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-2.5 mt-2">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
            <label className="text-xs font-bold text-slate-800 flex items-center gap-1.5">
              <Building className="w-3.5 h-3.5 text-blue-600" />
              <span>قسم المرور (اختياري):</span>
              <span className="text-[11px] font-normal text-slate-500">
                (يمكن تركه فارغاً أو تحديد أحد الأقسام الخمسة)
              </span>
            </label>

            {department && (
              <button
                type="button"
                onClick={() => {
                  setDepartment("");
                  setSelectedCategory("الكل");
                }}
                className="text-[11px] text-slate-500 hover:text-rose-600 font-semibold cursor-pointer"
              >
                مسح التحديد (عام / غير محدد)
              </button>
            )}
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <button
              type="button"
              onClick={() => {
                setDepartment("");
                setSelectedCategory("الكل");
              }}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                !department
                  ? "bg-blue-600 text-white shadow-xs"
                  : "bg-white text-slate-700 hover:bg-slate-100 border border-slate-300"
              }`}
            >
              عام / جميع الأقسام (اختياري)
            </button>

            {STANDARD_ROUND_DEPARTMENTS.map((dept) => {
              const isSelected = department === dept;
              return (
                <button
                  key={dept}
                  type="button"
                  onClick={() => {
                    setDepartment(dept);
                    setSelectedCategory(dept);
                  }}
                  className={`px-3.5 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1 cursor-pointer ${
                    isSelected
                      ? "bg-blue-600 text-white shadow-xs"
                      : "bg-white text-slate-700 hover:bg-blue-50 hover:border-blue-300 border border-slate-300"
                  }`}
                >
                  <span>{dept}</span>
                  {isSelected && <Check className="w-3.5 h-3.5" />}
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* 2. Observations Table with Auto-suggest on Typing & Injected Items */}
      <div ref={tableRef} className="bg-white rounded-xl p-5 sm:p-6 border border-slate-200 shadow-xs space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 pb-3">
          <div>
            <h3 className="font-bold text-slate-900 text-sm sm:text-base flex items-center gap-2">
              <span>جدول بنود وملاحظات التقرير المرصودة</span>
              <span className="text-xs font-bold text-blue-700 bg-blue-50 border border-blue-200 px-2.5 py-0.5 rounded-full">
                {observations.length} بند مسجل
              </span>
            </h3>
            <p className="text-xs text-slate-500">
              الملاحظات والتوصيات المضافة للتقرير — يمكنك تعديل أي نص أو موقع أو مسؤول بحرية
            </p>
          </div>

          <div className="flex items-center gap-2 flex-wrap">
            {/* 🌟 4-5 Balanced Preset Generator Button 🌟 */}
            <div className="relative">
              <button
                type="button"
                onClick={() => setIsBalancedMenuOpen(!isBalancedMenuOpen)}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold text-amber-900 bg-amber-50 hover:bg-amber-100 border border-amber-300 transition-all shadow-2xs cursor-pointer"
              >
                <Sparkles className="w-4 h-4 text-amber-600" />
                <span>⚡ تعبئة 4-5 ملاحظات متوازنة للأقسام</span>
                <ChevronDown className={`w-3 h-3 transition-transform ${isBalancedMenuOpen ? "rotate-180" : ""}`} />
              </button>

              {isBalancedMenuOpen && (
                <div
                  className="absolute left-0 mt-2 w-72 rounded-2xl bg-white shadow-2xl border border-slate-200 py-2 z-50 animate-in fade-in slide-in-from-top-2 duration-150 text-slate-800"
                  onClick={() => setIsBalancedMenuOpen(false)}
                >
                  <div className="px-3.5 py-1.5 border-b border-slate-100">
                    <p className="text-xs font-black text-slate-900">تعبئة سريعة بملاحظات متوازنة</p>
                    <p className="text-[11px] text-slate-500 font-medium">4 إلى 5 ملاحظات مع 1-2 لكل قسم</p>
                  </div>

                  <button
                    type="button"
                    onClick={() => handleLoadBalancedPreset(1)}
                    className="w-full px-3.5 py-2 text-right text-xs hover:bg-blue-50 transition-colors flex items-center justify-between group cursor-pointer"
                  >
                    <div>
                      <span className="font-bold text-slate-900 group-hover:text-blue-700 block">نموذج 1: عيادة، فحوصات، عمليات، إفاقة</span>
                      <span className="text-[10px] text-slate-500">5 ملاحظات</span>
                    </div>
                    <span className="text-[10px] bg-blue-100 text-blue-800 font-bold px-1.5 py-0.5 rounded">5 بنود</span>
                  </button>

                  <button
                    type="button"
                    onClick={() => handleLoadBalancedPreset(2)}
                    className="w-full px-3.5 py-2 text-right text-xs hover:bg-blue-50 transition-colors flex items-center justify-between group cursor-pointer"
                  >
                    <div>
                      <span className="font-bold text-slate-900 group-hover:text-blue-700 block">نموذج 2: عيادة، فحوصات، غسيل أيدي، عمليات</span>
                      <span className="text-[10px] text-slate-500">5 ملاحظات</span>
                    </div>
                    <span className="text-[10px] bg-blue-100 text-blue-800 font-bold px-1.5 py-0.5 rounded">5 بنود</span>
                  </button>

                  <button
                    type="button"
                    onClick={() => handleLoadBalancedPreset(3)}
                    className="w-full px-3.5 py-2 text-right text-xs hover:bg-blue-50 transition-colors flex items-center justify-between group cursor-pointer"
                  >
                    <div>
                      <span className="font-bold text-slate-900 group-hover:text-blue-700 block">نموذج 3: عيادة، فحوصات، عمليات، تعقيم</span>
                      <span className="text-[10px] text-slate-500">4 ملاحظات</span>
                    </div>
                    <span className="text-[10px] bg-emerald-100 text-emerald-800 font-bold px-1.5 py-0.5 rounded">4 بنود</span>
                  </button>

                  <button
                    type="button"
                    onClick={() => handleLoadBalancedPreset(4)}
                    className="w-full px-3.5 py-2 text-right text-xs hover:bg-blue-50 transition-colors flex items-center justify-between group cursor-pointer"
                  >
                    <div>
                      <span className="font-bold text-slate-900 group-hover:text-blue-700 block">نموذج 4: داخلي، فحوصات، عمليات، إفاقة</span>
                      <span className="text-[10px] text-slate-500">4 ملاحظات</span>
                    </div>
                    <span className="text-[10px] bg-emerald-100 text-emerald-800 font-bold px-1.5 py-0.5 rounded">4 بنود</span>
                  </button>

                  <div className="border-t border-slate-100 mt-1 pt-1">
                    <button
                      type="button"
                      onClick={() => handleLoadBalancedPreset()}
                      className="w-full px-3.5 py-2 text-right text-xs text-indigo-700 hover:bg-indigo-50 font-bold flex items-center gap-1.5 cursor-pointer"
                    >
                      <Sparkles className="w-3.5 h-3.5 text-amber-500" />
                      <span>توليد فوري لـ 5 ملاحظات متوازنة عشوائياً</span>
                    </button>
                  </div>
                </div>
              )}
            </div>

            <button
              type="button"
              onClick={() => setIsPickerModalOpen(true)}
              className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl text-xs font-bold text-white bg-indigo-600 hover:bg-indigo-700 transition-all shadow-xs cursor-pointer"
            >
              <Sparkles className="w-4 h-4" />
              <span>+ إضافة ملاحظة جديدة (من البنك والملخص)</span>
            </button>

            <button
              type="button"
              onClick={() => {
                setShowObservationBank(!showObservationBank);
                if (!showObservationBank) {
                  window.scrollTo({ top: 120, behavior: "smooth" });
                }
              }}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold text-blue-700 bg-blue-50 hover:bg-blue-100 border border-blue-200 transition-colors cursor-pointer"
            >
              <ListChecks className="w-4 h-4 text-blue-600" />
              <span>{showObservationBank ? "إخفاء بنك الأقسام" : "تصفح بنك الأقسام"}</span>
            </button>

            <button
              type="button"
              onClick={() => handleAddObservation()}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold text-slate-700 bg-white hover:bg-slate-100 border border-slate-300 transition-colors cursor-pointer"
            >
              <Plus className="w-4 h-4" />
              <span>+ سطر فارغ</span>
            </button>
          </div>
        </div>

        {observations.length === 0 ? (
          <div className="text-center py-10 border-2 border-dashed border-blue-200 rounded-2xl bg-blue-50/30 p-6 space-y-4">
            <div className="w-12 h-12 rounded-2xl bg-indigo-100 text-indigo-600 flex items-center justify-center mx-auto">
              <Sparkles className="w-6 h-6 text-indigo-600" />
            </div>
            <div>
              <p className="text-sm font-bold text-slate-800">لا توجد ملاحظات مسجلة في جدول التقرير حتى الآن</p>
              <p className="text-xs text-slate-500 mt-1">
                يمكنك التعبئة الفورية بـ 4-5 ملاحظات افتراضية متوازنة عبر الأقسام، أو الاختيار من الملخص وبنك الملاحظات
              </p>
            </div>

            <div className="flex flex-wrap justify-center gap-3 pt-2">
              <button
                type="button"
                onClick={() => handleLoadBalancedPreset(1)}
                className="px-5 py-2.5 rounded-xl text-xs sm:text-sm font-black bg-amber-500 text-slate-950 hover:bg-amber-400 shadow-md flex items-center gap-2 cursor-pointer"
              >
                <Sparkles className="w-4 h-4" />
                <span>⚡ تعبئة بتقرير افتراضي متوازن (5 ملاحظات للأقسام)</span>
              </button>

              <button
                type="button"
                onClick={() => setIsPickerModalOpen(true)}
                className="px-5 py-2.5 rounded-xl text-xs sm:text-sm font-bold bg-indigo-600 text-white hover:bg-indigo-700 shadow-md flex items-center gap-2 cursor-pointer"
              >
                <Sparkles className="w-4 h-4" />
                <span>فتح نافذة الملاحظات والملخص</span>
              </button>

              <button
                type="button"
                onClick={() => {
                  setShowObservationBank(true);
                  window.scrollTo({ top: 100, behavior: "smooth" });
                }}
                className="px-4 py-2.5 rounded-xl text-xs font-bold bg-blue-50 text-blue-800 border border-blue-200 hover:bg-blue-100 flex items-center gap-1.5 cursor-pointer"
              >
                <ListChecks className="w-4 h-4" />
                <span>تصفح بنك الأقسام بالصفحة</span>
              </button>

              <button
                type="button"
                onClick={() => handleAddObservation()}
                className="px-4 py-2.5 rounded-xl text-xs font-bold bg-white text-slate-700 border border-slate-300 hover:bg-slate-50 flex items-center gap-1.5 cursor-pointer"
              >
                <Plus className="w-4 h-4" />
                <span>+ إضافة سطر يدوياً</span>
              </button>
            </div>
          </div>
        ) : (
          <div className="space-y-5">
            {observations.map((obs, idx) => {
              const isDropdownOpen = activeSuggestionRowId === obs.id;
              const suggestions = getSuggestionsForRow(obs);

              return (
                <div
                  key={obs.id || idx}
                  className="p-4 sm:p-5 rounded-2xl bg-slate-50/80 border border-slate-300 space-y-3 relative shadow-2xs transition-all hover:border-slate-400"
                >
                  {/* Row Header */}
                  <div className="flex items-center justify-between border-b border-slate-200 pb-2.5">
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-bold text-slate-800 bg-white border border-slate-300 px-2.5 py-0.5 rounded-md shadow-2xs">
                        بند #{idx + 1}
                      </span>
                      {obs.dueDate && (
                        <span className="text-[11px] text-slate-500 bg-slate-100 px-2 py-0.5 rounded">
                          المدة: {obs.dueDate}
                        </span>
                      )}
                    </div>

                    <button
                      type="button"
                      onClick={() => handleRemoveObservation(obs.id)}
                      className="text-rose-500 hover:text-rose-700 hover:bg-rose-50 px-2 py-1 rounded-md text-xs flex items-center gap-1 cursor-pointer transition-colors"
                      title="حذف هذا البند"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                      <span>حذف</span>
                    </button>
                  </div>

                  {/* Main Inputs Grid */}
                  <div className="grid grid-cols-1 sm:grid-cols-12 gap-3">
                    
                    {/* Location Field - Optional with 5 Choices: عيادة / فحوصات / قسم داخلي / عمليات / إفاقة */}
                    <div className="sm:col-span-4 space-y-1.5">
                      <div className="flex items-center justify-between">
                        <label className="block text-xs font-bold text-slate-700">
                          <span>القسم / الموقع</span>
                          <span className="text-[11px] font-normal text-slate-400 mr-1">(اختياري)</span>
                        </label>
                        {obs.location && (
                          <button
                            type="button"
                            onClick={() => handleUpdateObservation(obs.id, "location", "")}
                            className="text-[10px] text-slate-400 hover:text-rose-500 font-medium cursor-pointer"
                          >
                            مسح
                          </button>
                        )}
                      </div>

                      {/* Dropdown Select for the 5 Standard Locations + Optional/Custom */}
                      <select
                        value={
                          STANDARD_ROUND_DEPARTMENTS.includes(obs.location as any) || obs.location === "افاقة"
                            ? (obs.location === "افاقة" ? "إفاقة" : obs.location)
                            : obs.location
                            ? "custom"
                            : ""
                        }
                        onChange={(e) => {
                          const val = e.target.value;
                          if (val === "custom") {
                            if (STANDARD_ROUND_DEPARTMENTS.includes(obs.location as any) || obs.location === "افاقة") {
                              handleUpdateObservation(obs.id, "location", "");
                            }
                          } else {
                            handleUpdateObservation(obs.id, "location", val);
                          }
                        }}
                        className="w-full text-xs sm:text-sm rounded-lg border border-slate-300 p-2 bg-white font-bold text-slate-800 focus:ring-2 focus:ring-blue-500 focus:outline-hidden"
                      >
                        <option value="">-- اختياري (بدون تحديد) --</option>
                        <option value="عيادة">عيادة</option>
                        <option value="فحوصات">فحوصات</option>
                        <option value="قسم داخلي">قسم داخلي</option>
                        <option value="عمليات">عمليات</option>
                        <option value="إفاقة">إفاقة</option>
                        <option value="custom">موقع / قسم آخر (مخصص)...</option>
                      </select>

                      {/* Custom text field if custom is chosen or text doesn't match standard */}
                      {obs.location !== "" &&
                        !STANDARD_ROUND_DEPARTMENTS.includes(obs.location as any) &&
                        obs.location !== "افاقة" && (
                          <input
                            type="text"
                            value={obs.location || ""}
                            onChange={(e) => handleUpdateObservation(obs.id, "location", e.target.value)}
                            placeholder="اكتب الموقع أو القسم المخصص..."
                            className="w-full text-xs rounded-lg border border-blue-300 p-1.5 bg-blue-50/60 font-bold text-slate-800 focus:ring-2 focus:ring-blue-500 focus:outline-hidden"
                          />
                        )}

                      {/* Quick 1-click pills for the 5 choices */}
                      <div className="flex flex-wrap items-center gap-1 pt-0.5">
                        {STANDARD_ROUND_DEPARTMENTS.map((dept) => {
                          const isChosen =
                            obs.location === dept || (dept === "إفاقة" && obs.location === "افاقة");
                          return (
                            <button
                              key={dept}
                              type="button"
                              onClick={() =>
                                handleUpdateObservation(
                                  obs.id,
                                  "location",
                                  isChosen ? "" : dept
                                )
                              }
                              className={`text-[10px] px-2 py-0.5 rounded font-bold transition-all cursor-pointer ${
                                isChosen
                                  ? "bg-blue-600 text-white shadow-2xs"
                                  : "bg-white text-slate-600 hover:bg-blue-50 hover:text-blue-700 hover:border-blue-300 border border-slate-200"
                              }`}
                            >
                              {dept}
                            </button>
                          );
                        })}
                      </div>
                    </div>

                    {/* Observation Field with Real-time Suggestions Popover */}
                    <div className="sm:col-span-8 relative">
                      <div className="flex items-center justify-between mb-1">
                        <label className="text-xs font-bold text-slate-700 flex items-center gap-1.5">
                          <span>الملاحظة (القصور أو عدم المطابقة المرصودة)</span>
                        </label>

                        <div className="flex items-center gap-2">
                          {/* Toggle Suggestions button */}
                          <button
                            type="button"
                            onClick={() => {
                              setActiveSuggestionRowId(isDropdownOpen ? null : obs.id);
                            }}
                            className={`text-[11px] font-bold px-2 py-0.5 rounded-md border flex items-center gap-1 transition-colors cursor-pointer ${
                              isDropdownOpen
                                ? "bg-blue-600 text-white border-blue-600"
                                : "text-blue-700 bg-blue-50 border-blue-200 hover:bg-blue-100"
                            }`}
                            title="عرض قائمة الملاحظات المقترحة لهذا البند"
                          >
                            <Lightbulb className="w-3 h-3 text-amber-500 fill-amber-400" />
                            <span>{isDropdownOpen ? "إغلاق المقترحات" : "اقتراحات"}</span>
                            <ChevronDown className={`w-3 h-3 transition-transform ${isDropdownOpen ? "rotate-180" : ""}`} />
                          </button>

                          {/* AI Correction Generator */}
                          <button
                            type="button"
                            onClick={() => handleAiSuggestCorrectiveAction(idx)}
                            disabled={aiLoadingIdx === idx}
                            className="text-[11px] font-bold text-indigo-700 hover:text-indigo-900 bg-indigo-50 border border-indigo-200 px-2 py-0.5 rounded-md inline-flex items-center gap-1 cursor-pointer"
                            title="اقتراح الإجراء التصحيحي بالذكاء الاصطناعي"
                          >
                            <Sparkles className="w-3 h-3 text-indigo-600" />
                            <span>{aiLoadingIdx === idx ? "جاري..." : "اقتراح AI"}</span>
                          </button>
                        </div>
                      </div>

                      {/* Observation Textarea */}
                      <textarea
                        rows={2}
                        value={obs.observation}
                        onChange={(e) => {
                          handleUpdateObservation(obs.id, "observation", e.target.value);
                          if (!isDropdownOpen) {
                            setActiveSuggestionRowId(obs.id);
                          }
                        }}
                        onFocus={() => {
                          setActiveSuggestionRowId(obs.id);
                        }}
                        placeholder="ابدأ بكتابة الملاحظة أو عدل عليها..."
                        className="w-full text-xs sm:text-sm rounded-lg border border-slate-300 p-2.5 bg-white text-slate-900 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 focus:outline-hidden"
                        required
                      />

                      {/* Floating Autocomplete */}
                      {isDropdownOpen && (
                        <div className="absolute top-full right-0 left-0 mt-1 z-40 bg-white rounded-xl shadow-2xl border border-blue-300 p-3 space-y-2.5 animate-in fade-in slide-in-from-top-2 max-w-2xl">
                          
                          {/* Dropdown Header & Category Selector */}
                          <div className="space-y-1.5 border-b border-slate-100 pb-2">
                            <div className="flex items-center justify-between">
                              <div className="flex items-center gap-1.5 text-xs font-bold text-slate-800">
                                <Lightbulb className="w-4 h-4 text-amber-500 fill-amber-400" />
                                <span>ملاحظات مقترحة مطابقة ({suggestions.length})</span>
                                <span className="text-[10px] font-semibold text-amber-700 bg-amber-50 px-2 py-0.5 rounded-full border border-amber-200">
                                  ⭐ الملخص (35) في البداية
                                </span>
                              </div>

                              <button
                                type="button"
                                onClick={() => setActiveSuggestionRowId(null)}
                                className="text-slate-400 hover:text-slate-700 p-1 rounded-md hover:bg-slate-100 transition-colors"
                              >
                                <X className="w-4 h-4" />
                              </button>
                            </div>

                            {/* Quick Category Filter Bar */}
                            <div className="flex items-center gap-1 overflow-x-auto py-0.5 text-[10px] scrollbar-none">
                              <button
                                type="button"
                                onClick={() => setDropdownCategoryFilter("الكل")}
                                className={`px-2 py-0.5 rounded font-bold whitespace-nowrap cursor-pointer transition-colors ${
                                  dropdownCategoryFilter === "الكل"
                                    ? "bg-slate-800 text-white"
                                    : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                                }`}
                              >
                                الكل
                              </button>
                              <button
                                type="button"
                                onClick={() => setDropdownCategoryFilter("⭐ ملخص اليوم (35)")}
                                className={`px-2 py-0.5 rounded font-bold whitespace-nowrap cursor-pointer transition-colors ${
                                  dropdownCategoryFilter === "⭐ ملخص اليوم (35)"
                                    ? "bg-amber-600 text-white"
                                    : "bg-amber-50 text-amber-800 border border-amber-200 hover:bg-amber-100"
                                }`}
                              >
                                ⭐ ملخص اليوم (35)
                              </button>
                              {["عيادة", "فحوصات", "قسم داخلي", "عمليات", "إفاقة"].map((dept) => (
                                <button
                                  key={dept}
                                  type="button"
                                  onClick={() => setDropdownCategoryFilter(dept)}
                                  className={`px-2 py-0.5 rounded font-bold whitespace-nowrap cursor-pointer transition-colors ${
                                    dropdownCategoryFilter === dept
                                      ? "bg-blue-600 text-white"
                                      : "bg-blue-50 text-blue-700 hover:bg-blue-100"
                                  }`}
                                >
                                  {dept}
                                </button>
                              ))}
                            </div>
                          </div>

                          {/* Suggestions List */}
                          <div className="max-h-64 overflow-y-auto space-y-1.5 pr-0.5 divide-y divide-slate-100">
                            {suggestions.length === 0 ? (
                              <div className="py-4 text-center text-xs text-slate-500">
                                لا توجد اقتراحات مطابقة تماماً لنص البحث
                              </div>
                            ) : (
                              suggestions.slice(0, 20).map((item) => {
                                const isSummary = isTodaySummaryObservation(item.id);
                                return (
                                  <div
                                    key={item.id}
                                    onClick={() => handleSelectSuggestionForRow(obs.id, item)}
                                    className={`pt-2 first:pt-0 p-2.5 rounded-lg cursor-pointer transition-colors text-right group border ${
                                      isSummary
                                        ? "bg-amber-50/40 hover:bg-amber-50 border-amber-200/80 hover:border-amber-400"
                                        : "hover:bg-blue-50/80 border-transparent hover:border-blue-200"
                                    }`}
                                  >
                                    <div className="flex items-center justify-between gap-2 mb-1">
                                      <div className="flex items-center gap-1.5 flex-wrap">
                                        {isSummary && (
                                          <span className="text-[9px] font-bold text-amber-900 bg-amber-200/90 px-2 py-0.5 rounded border border-amber-400 flex items-center gap-1 shadow-2xs">
                                            ⭐ من ملخص اليوم (35)
                                          </span>
                                        )}
                                        {item.isCustom && (
                                          <span className="text-[9px] font-bold text-purple-800 bg-purple-100/90 px-1.5 py-0.2 rounded border border-purple-300 flex items-center gap-0.5">
                                            سجل محفوظ
                                          </span>
                                        )}
                                        <span className="text-[10px] font-bold text-blue-800 bg-blue-50 px-1.5 py-0.2 rounded border border-blue-200">
                                          {item.location}
                                        </span>
                                        <span className="text-[10px] text-slate-500 font-medium">
                                          ({item.category})
                                        </span>
                                      </div>

                                      <span className="text-[11px] font-bold text-blue-600 opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-0.5">
                                        <Check className="w-3 h-3" />
                                        <span>اختيار</span>
                                      </span>
                                    </div>

                                    <p className={`text-xs font-bold leading-snug ${isSummary ? "text-amber-950" : "text-slate-900 group-hover:text-blue-950"}`}>
                                      {item.observation}
                                    </p>
                                    <p className="text-[11px] text-slate-600 mt-1 line-clamp-1">
                                      <strong className="text-blue-700">التوصية:</strong> {item.recommendation}
                                    </p>
                                  </div>
                                );
                              })
                            )}
                          </div>
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Recommendation & Responsible Grid */}
                  <div className="grid grid-cols-1 sm:grid-cols-12 gap-3 pt-1">
                    {/* Recommendations */}
                    <div className="sm:col-span-8">
                      <div className="flex items-center justify-between mb-1">
                        <label className="block text-xs font-bold text-slate-700">
                          التوصيات / الإجراء التصحيحي المطلوب
                        </label>
                        {autoGeneratedRows[obs.id] && obs.recommendation && (
                          <div className="flex items-center gap-1">
                            <span className="text-[10px] font-bold text-emerald-700 bg-emerald-50 border border-emerald-200 px-2 py-0.5 rounded-full flex items-center gap-1">
                              <Sparkles className="w-2.5 h-2.5 text-emerald-600" />
                              <span>تم التوليد تلقائياً</span>
                            </span>
                            <button
                              type="button"
                              onClick={() => handleAiSuggestCorrectiveAction(idx)}
                              title="إعادة التوليد"
                              className="text-[10px] text-slate-500 hover:text-indigo-600 underline font-medium cursor-pointer"
                            >
                              تحديث
                            </button>
                          </div>
                        )}
                      </div>
                      <textarea
                        rows={2}
                        value={obs.recommendation}
                        onChange={(e) =>
                          handleUpdateObservation(obs.id, "recommendation", e.target.value)
                        }
                        placeholder="التوصية أو الإجراء التصحيحي المعتمد لتلافي القصور (يتم توليده تلقائياً عند كتابة الملاحظة)..."
                        className={`w-full text-xs sm:text-sm rounded-lg border p-2.5 transition-all ${
                          autoGeneratedRows[obs.id]
                            ? "bg-emerald-50/30 border-emerald-300 text-slate-900 focus:ring-2 focus:ring-emerald-500"
                            : "bg-white border-slate-300 text-slate-900 focus:ring-2 focus:ring-blue-500"
                        }`}
                        required
                      />
                    </div>

                    {/* Responsible */}
                    <div className="sm:col-span-4">
                      <label className="block text-xs font-bold text-slate-700 mb-1">
                        المسؤول عن التنفيذ
                      </label>
                      <input
                        type="text"
                        value={obs.responsible}
                        onChange={(e) =>
                          handleUpdateObservation(obs.id, "responsible", e.target.value)
                        }
                        placeholder="مشرف التمريض / مسؤول القسم"
                        className="w-full text-xs sm:text-sm rounded-lg border border-slate-300 p-2.5 bg-white text-slate-900 font-semibold focus:ring-2 focus:ring-blue-500 focus:outline-hidden"
                        required
                      />
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* 🌟 3. CATEGORIZED OBSERVATION BANK WITH CHECKBOXES (مقسمة إلى أقسام بمربعات اختيار) 🌟 */}
      {showObservationBank && (
        <div className="bg-gradient-to-br from-blue-50/70 via-white to-slate-50 rounded-2xl p-4 sm:p-6 border-2 border-blue-200 shadow-sm space-y-4 animate-in fade-in duration-200">
          
          {/* Header */}
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 border-b border-blue-100 pb-3">
            <div className="flex items-start gap-3">
              <div className="w-9 h-9 rounded-xl bg-blue-600 text-white flex items-center justify-center shadow-2xs shrink-0 mt-0.5">
                <ListChecks className="w-5 h-5" />
              </div>
              <div>
                <div className="flex items-center gap-2 flex-wrap">
                  <h3 className="font-extrabold text-slate-900 text-sm sm:text-base">
                    بنك ملاحظات مكافحة العدوى المعتمدة (مقسمة حسب الأقسام)
                  </h3>
                  <span className="text-[11px] font-bold px-2 py-0.5 rounded-full bg-blue-100 text-blue-800 border border-blue-200">
                    {allLibraryItems.length} ملاحظة معتمدة
                  </span>
                </div>
                <p className="text-xs text-slate-600 mt-0.5">
                  ضع علامة داخل <strong>المربع الصغير ☑️</strong> أمام الملاحظات المرصودة من أي قسم، ثم اضغط على زر <strong>(إضافة للتقرير)</strong> بالأسفل أو بالأعلى.
                </p>
              </div>
            </div>

            {/* Action Buttons: Add Selected to Report */}
            <div className="flex items-center gap-2 flex-wrap self-start md:self-auto">
              {selectedItemIds.length > 0 && (
                <button
                  type="button"
                  onClick={handleClearSelections}
                  className="px-2.5 py-1.5 rounded-lg text-xs font-semibold text-slate-600 hover:text-slate-900 hover:bg-slate-100 transition-colors cursor-pointer"
                >
                  إلغاء التحديد ({selectedItemIds.length})
                </button>
              )}

              <button
                type="button"
                onClick={handleAddSelectedToReport}
                disabled={selectedItemIds.length === 0}
                className={`inline-flex items-center gap-2 px-4 py-2 rounded-xl text-xs sm:text-sm font-black transition-all shadow-md cursor-pointer ${
                  selectedItemIds.length > 0
                    ? "bg-emerald-600 hover:bg-emerald-700 text-white ring-2 ring-emerald-400 animate-pulse"
                    : "bg-slate-200 text-slate-400 cursor-not-allowed"
                }`}
              >
                <Plus className="w-4 h-4 stroke-[3]" />
                <span>إضافة للتقرير ({selectedItemIds.length})</span>
              </button>
            </div>
          </div>

          {/* Search & Severity Filters */}
          <div className="flex flex-col sm:flex-row gap-2.5">
            <div className="relative grow">
              <Search className="w-4 h-4 text-slate-400 absolute right-3.5 top-3" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="ابحث في جميع الملاحظات (مثال: تعقيم، كراتين، غسيل أيدي، نفايات، كمامة، هواء، ضغط...)"
                className="w-full pr-10 pl-3 py-2 text-xs sm:text-sm bg-white rounded-xl border border-slate-300 focus:ring-2 focus:ring-blue-500 focus:outline-hidden font-medium"
              />
              {searchQuery && (
                <button
                  type="button"
                  onClick={() => setSearchQuery("")}
                  className="absolute left-3 top-2.5 text-slate-400 hover:text-slate-600"
                >
                  <X className="w-4 h-4" />
                </button>
              )}
            </div>

            {/* Quick Bulk Select Button */}
            <div className="flex items-center gap-2 shrink-0">
              <button
                type="button"
                onClick={handleSelectAllVisible}
                className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold bg-white hover:bg-blue-50 text-blue-700 border border-blue-200 transition-colors cursor-pointer"
              >
                <CheckSquare className="w-3.5 h-3.5 text-blue-600" />
                <span>تحديد الكل في هذا العرض ({filteredBankItems.length})</span>
              </button>

              <div className="flex items-center bg-white p-1 rounded-xl border border-slate-200 text-[11px]">
                <button
                  type="button"
                  onClick={() => setSeverityFilter("all")}
                  className={`px-2 py-1 rounded-lg font-bold transition-colors ${
                    severityFilter === "all" ? "bg-slate-800 text-white" : "text-slate-600 hover:bg-slate-100"
                  }`}
                >
                  الكل
                </button>
                <button
                  type="button"
                  onClick={() => setSeverityFilter("critical")}
                  className={`px-2 py-1 rounded-lg font-bold transition-colors ${
                    severityFilter === "critical" ? "bg-rose-600 text-white" : "text-rose-700 hover:bg-rose-50"
                  }`}
                >
                  حرجة / فوري
                </button>
                <button
                  type="button"
                  onClick={() => setSeverityFilter("high")}
                  className={`px-2 py-1 rounded-lg font-bold transition-colors ${
                    severityFilter === "high" ? "bg-amber-600 text-white" : "text-amber-700 hover:bg-amber-50"
                  }`}
                >
                  عالية
                </button>
              </div>
            </div>
          </div>

          {/* Department / Category Tabs */}
          <div className="flex items-center gap-1.5 overflow-x-auto pb-1.5 no-scrollbar border-b border-slate-200">
            {categories.map((cat) => {
              const count =
                cat === "الكل"
                  ? allLibraryItems.length
                  : allLibraryItems.filter((i) => i.category === cat).length;
              
              const isSelected = selectedCategory === cat;
              return (
                <button
                  key={cat}
                  type="button"
                  onClick={() => setSelectedCategory(cat)}
                  className={`px-3 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap shrink-0 transition-all flex items-center gap-1.5 cursor-pointer ${
                    isSelected
                      ? "bg-blue-600 text-white shadow-xs"
                      : "bg-white text-slate-700 hover:bg-slate-100 border border-slate-200"
                  }`}
                >
                  <span>{cat}</span>
                  <span
                    className={`text-[10px] px-1.5 py-0.2 rounded-full font-black ${
                      isSelected ? "bg-white/20 text-white" : "bg-slate-100 text-slate-600"
                    }`}
                  >
                    {count}
                  </span>
                </button>
              );
            })}
          </div>

          {/* Grouped Categorized Items List with Checkboxes */}
          <div className="space-y-4 max-h-[480px] overflow-y-auto pr-1 pl-1 bg-white/60 p-3 rounded-2xl border border-blue-100">
            {Object.keys(groupedBankItems).length === 0 ? (
              <div className="text-center py-12 text-slate-500 space-y-2">
                <Lightbulb className="w-8 h-8 text-amber-400 mx-auto" />
                <p className="text-sm font-bold">لا توجد ملاحظات مطابقة لمعايير البحث أو التصفية الحالية</p>
                <p className="text-xs text-slate-400">جرب كتابة كلمات بحث أخرى أو اختر تصنيف "الكل"</p>
              </div>
            ) : (
              Object.entries(groupedBankItems).map(([categoryName, items]) => (
                <div
                  key={categoryName}
                  className="bg-white rounded-2xl p-3.5 border border-slate-200 shadow-2xs space-y-2.5"
                >
                  {/* Category Group Header */}
                  <div className="flex items-center justify-between border-b border-slate-100 pb-2">
                    <div className="flex items-center gap-2">
                      <div className="w-2.5 h-2.5 rounded-full bg-blue-600" />
                      <h4 className="font-extrabold text-slate-900 text-xs sm:text-sm">
                        {categoryName}
                      </h4>
                      <span className="text-[11px] font-bold text-slate-500 bg-slate-100 px-2 py-0.2 rounded-md">
                        {items.length} ملاحظات
                      </span>
                    </div>

                    <button
                      type="button"
                      onClick={() => {
                        const catIds = items.map((i) => i.id);
                        const allCatSelected = catIds.every((id) => selectedItemIds.includes(id));
                        if (allCatSelected) {
                          setSelectedItemIds((prev) => prev.filter((id) => !catIds.includes(id)));
                        } else {
                          setSelectedItemIds((prev) => Array.from(new Set([...prev, ...catIds])));
                        }
                      }}
                      className="text-[11px] font-bold text-blue-700 hover:text-blue-900 hover:bg-blue-50 px-2 py-0.5 rounded cursor-pointer"
                    >
                      تحديد كل قسم ({categoryName.split(" ")[0]})
                    </button>
                  </div>

                  {/* Observation Cards with Checkboxes */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
                    {items.map((item) => {
                      const isChecked = selectedItemIds.includes(item.id);

                      return (
                        <div
                          key={item.id}
                          onClick={() => handleToggleItemSelection(item.id)}
                          className={`p-3.5 rounded-xl border-2 transition-all cursor-pointer text-right flex items-start gap-3 select-none ${
                            isChecked
                              ? "bg-blue-50/90 border-blue-500 shadow-xs ring-1 ring-blue-500"
                              : "bg-white hover:bg-slate-50 border-slate-200 hover:border-blue-300"
                          }`}
                        >
                          {/* 🌟 Small Checkbox 🌟 */}
                          <div className="pt-0.5 shrink-0">
                            <div
                              className={`w-5 h-5 rounded-md flex items-center justify-center transition-all ${
                                isChecked
                                  ? "bg-blue-600 text-white shadow-2xs"
                                  : "border-2 border-slate-400 bg-white hover:border-blue-500"
                              }`}
                            >
                              {isChecked && <Check className="w-3.5 h-3.5 stroke-[3]" />}
                            </div>
                          </div>

                          {/* Content */}
                          <div className="grow space-y-1.5 min-w-0">
                            {/* Badges */}
                            <div className="flex items-center justify-between gap-1.5 flex-wrap">
                              <span className="text-[10px] font-bold text-blue-800 bg-blue-100/80 px-2 py-0.5 rounded-md flex items-center gap-1">
                                <Building className="w-3 h-3 text-blue-600" />
                                {item.location}
                              </span>

                              <div className="flex items-center gap-1">
                                {item.severity === "critical" && (
                                  <span className="text-[10px] font-bold text-rose-700 bg-rose-50 px-1.5 py-0.2 rounded border border-rose-200 flex items-center gap-0.5">
                                    <AlertTriangle className="w-2.5 h-2.5" /> فوري
                                  </span>
                                )}
                                {item.severity === "high" && (
                                  <span className="text-[10px] font-bold text-amber-700 bg-amber-50 px-1.5 py-0.2 rounded border border-amber-200">
                                    عالي
                                  </span>
                                )}
                              </div>
                            </div>

                            {/* Observation Text */}
                            <p className="text-xs font-bold text-slate-900 leading-snug">
                              <span className="text-rose-700 font-extrabold ml-1">الملاحظة:</span>
                              {item.observation}
                            </p>

                            {/* Recommendation Text */}
                            <p className="text-[11px] text-slate-700 leading-snug">
                              <span className="text-blue-700 font-bold ml-1">التوصية:</span>
                              {item.recommendation}
                            </p>

                            {/* Metadata */}
                            <div className="flex items-center justify-between text-[10px] text-slate-500 pt-1 border-t border-slate-100">
                              <span><strong>المسؤول:</strong> {item.responsible}</span>
                              <span><strong>المدة:</strong> {item.duration}</span>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ))
            )}
          </div>

          {/* Sticky Bottom Bar within the Bank for Easy Insertion */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-2 border-t border-blue-100 bg-white/80 p-3 rounded-xl">
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold text-slate-800">
                إجمالي الملاحظات المحددة حالياً:
              </span>
              <span className="px-2.5 py-0.5 rounded-full bg-blue-600 text-white font-black text-xs">
                {selectedItemIds.length} ملاحظة
              </span>
            </div>

            <button
              type="button"
              onClick={handleAddSelectedToReport}
              disabled={selectedItemIds.length === 0}
              className={`inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl text-xs sm:text-sm font-black transition-all shadow-md cursor-pointer ${
                selectedItemIds.length > 0
                  ? "bg-emerald-600 hover:bg-emerald-700 text-white shadow-emerald-600/30"
                  : "bg-slate-200 text-slate-400 cursor-not-allowed"
              }`}
            >
              <Plus className="w-4 h-4 stroke-[3]" />
              <span>إضافة الملاحظات المحددة للتقرير ({selectedItemIds.length})</span>
            </button>
          </div>
        </div>
      )}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 pt-4 border-t border-slate-200">
        <div className="flex items-center gap-2 flex-wrap">
          <button
            type="button"
            onClick={() => setIsPickerModalOpen(true)}
            className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl text-xs sm:text-sm font-bold text-white bg-indigo-600 hover:bg-indigo-700 transition-all shadow-xs cursor-pointer"
          >
            <Sparkles className="w-4 h-4" />
            <span>+ إضافة ملاحظة جديدة (من البنك والملخص)</span>
          </button>

          <button
            type="button"
            onClick={() => handleAddObservation()}
            className="inline-flex items-center gap-1.5 px-3.5 py-2.5 rounded-xl text-xs sm:text-sm font-semibold text-slate-700 bg-white hover:bg-slate-100 border border-slate-300 transition-colors cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            <span>+ إضافة سطر فارغ</span>
          </button>
        </div>

        <div className="flex items-center gap-2 justify-end">
          <button
            type="button"
            onClick={onCancel}
            className="px-5 py-2.5 rounded-xl text-xs sm:text-sm font-semibold text-slate-700 bg-white border border-slate-300 hover:bg-slate-50 transition-colors cursor-pointer"
          >
            إلغاء
          </button>

          <button
            type="submit"
            className="inline-flex items-center gap-2 px-6 py-2.5 rounded-xl text-xs sm:text-sm font-bold text-white bg-blue-600 hover:bg-blue-700 transition-colors shadow-md cursor-pointer"
          >
            <Save className="w-4 h-4" />
            <span>حفظ تقرير المرور ومعاينته</span>
          </button>
        </div>
      </div>

      {/* 🌟 Rich Observations & Today Summary Picker Modal 🌟 */}
      <RoundObservationPickerModal
        isOpen={isPickerModalOpen}
        onClose={() => setIsPickerModalOpen(false)}
        onSelectObservation={handleSelectObservationFromPicker}
        onSelectMultipleObservations={handleSelectMultipleObservationsFromPicker}
        onAddEmptyRow={() => handleAddObservation()}
        currentDepartment={department}
      />

    </form>
  );
};

